### ISSUE TITLE
[question] How to reduce memory usage when controlling multiple devices?

### ISSUE THREAD

**Issue by dhebbeker** [stm32duino/VL53L1#25]
I am using this library to control 4 VL53L1 devices. For this I defined 4 objects of the class `VL53L1`. Unfortunately each object uses 9kB dynamic memory. This meets my expectations from the information given in the user manual UM2133 (8kB).

I am compiling with xtensa-lx106-elf-g++ (GCC) 4.8.2 and `-Os`.
I defined `VL53L1_MAX_RANGE_RESULTS` to 1.

These 4 objects use nearly half of the RAM available on the ESP8266 I use.

Do you have any recommendations on how to safe some memory? I only need simple range measurement data from each device.
Is it a good idea to use only one object and switch between the devices? What are the drawbacks?

**Comment by cparata** [comment]
Hi @dhebbeker ,
if you use only one object, how can you switch from a sensor to the other? The object contains the I2C address and the the I2C instance that can change from a sensor to the other. In my opinion, the only possibility to reduce the footprint of the library could be to introduce some defines to enable/disable some fields of the object and the related methods if they are not used in the common use case. In this way we can put these defines in the file that you added for the custom configuration of the sensor and so we can enable/disable them according the use case. Removing unused struct should help to improve the footprint of the library. Unfortunately, I do not have bandwidth to work on it. If you want, you can try to improve the library in that way.
Best Regards,
Carlo
